version: '3.8'
services:
  db1:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_DB=origination
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db1:/var/lib/postgresql/data

  db2:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_DB=pe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5431:5432'
    volumes:
      - db2:/var/lib/postgresql/data

volumes:
  db1:
    driver: local
  db2:
    driver: local